['abeam', 'ameba']
['abode', 'adobe']
['abort', 'tabor']
['acerb', 'brace', 'caber']
['acned', 'dance']
['acorn', 'racon']
['acres', 'ceras', 'scare']
['actin', 'antic']
['adder', 'dread']
['adept', 'taped']
['adorn', 'nardo', 'radon']
['afire', 'feria']
['agism', 'sigma']
['agree', 'eager', 'eagre', 'ragee']
['alert', 'alter', 'later', 'ratel']
['algin', 'align', 'ligan']
['alias', 'salai']
['alien', 'aline', 'anile']
['allot', 'atoll']
['alloy', 'loyal']
['allyl', 'lally']
['aloft', 'float']
['alone', 'anole']
['aloof', 'loofa']
['amain', 'anima', 'mania']
['amass', 'msasa']
['amber', 'bream']
['amble', 'blame']
['ameer', 'ramee']
['amend', 'named']
['amide', 'media']
['amine', 'anime']
['amino', 'nomia']
['amnic', 'manic']
['ample', 'maple']
['amply', 'palmy']
['angel', 'angle', 'glean']
['anger', 'range']
['angry', 'rangy']
['apery', 'payer', 'repay']
['apnea', 'paean']
['appal', 'papal']
['aptly', 'platy']
['arced', 'cadre', 'cedar']
['ardeb', 'bared', 'beard', 'bread', 'debar']
['arete', 'eater']
['argon', 'groan', 'orang', 'organ']
['argot', 'groat']
['argue', 'auger']
['arise', 'raise']
['armed', 'derma', 'dream']
['armet', 'mater', 'tamer']
['aroid', 'radio']
['arson', 'sonar']
['ascot', 'coast', 'costa']
['asper', 'parse', 'spare', 'spear']
['asset', 'seats', 'tasse']
['aster', 'rates', 'stare', 'tears', 'teras']
['astir', 'sitar', 'stair', 'stria']
['atone', 'oaten']
['atrip', 'tapir']
['avert', 'trave']
['azido', 'diazo']
['badly', 'baldy']
['bagel', 'gable', 'gleba']
['bairn', 'brain']
['baker', 'brake', 'break']
['balas', 'balsa', 'basal']
['barky', 'braky']
['based', 'beads']
['basin', 'sabin']
['baste', 'beast', 'beats', 'tabes']
['beamy', 'maybe']
['bedew', 'dweeb']
['bedim', 'imbed']
['being', 'binge']
['below', 'bowel', 'elbow']
['bidet', 'debit']
['biter', 'tribe']
['blare', 'blear']
['blase', 'sable']
['blate', 'bleat', 'table']
['bleep', 'plebe']
['board', 'broad', 'dobra']
['boast', 'sabot']
['boney', 'ebony']
['bonus', 'bosun']
['booby', 'yobbo']
['bored', 'robed']
['braid', 'rabid']
['braze', 'zebra']
['brief', 'fiber', 'fibre']
['broth', 'throb']
['bruin', 'burin']
['brunt', 'burnt']
['brush', 'shrub']
['brute', 'buret', 'rebut', 'tuber']
['bugle', 'bulge']
['burro', 'rubor']
['cager', 'grace']
['canid', 'nicad']
['canoe', 'ocean']
['canto', 'cotan']
['caper', 'crape', 'pacer', 'recap']
['caret', 'carte', 'cater', 'crate', 'react', 'trace']
['carob', 'cobra']
['carol', 'claro', 'coral']
['carom', 'macro']
['carve', 'crave']
['cause', 'sauce']
['cense', 'scene']
['chart', 'ratch']
['cheap', 'peach']
['cheat', 'theca']
['chela', 'leach']
['chert', 'retch']
['chili', 'lichi']
['chime', 'hemic']
['chine', 'niche']
['choir', 'ichor']
['chore', 'ocher', 'ochre']
['churl', 'lurch']
['churn', 'runch']
['cider', 'dicer']
['civet', 'evict']
['clade', 'decal', 'laced']
['clasp', 'scalp']
['clean', 'lance']
['clear', 'lacer']
['cleat', 'eclat']
['close', 'socle']
['cloud', 'could']
['coder', 'credo', 'decor']
['codon', 'condo']
['cooly', 'coyol']
['copse', 'scope']
['cords', 'scrod']
['corky', 'rocky']
['corny', 'crony']
['couth', 'touch']
['crake', 'creak']
['craps', 'scarp', 'scrap']
['cream', 'macer']
['creep', 'crepe']
['crier', 'ricer']
['crisp', 'scrip']
['crude', 'cured']
['cruel', 'lucre', 'ulcer']
['cruet', 'curet', 'eruct', 'truce']
['cruse', 'curse', 'sucre']
['crust', 'curst']
['cuffs', 'scuff']
['cumin', 'mucin']
['cutis', 'ictus']
['cyder', 'decry']
['dairy', 'diary']
['damar', 'drama']
['daraf', 'farad']
['deary', 'ready']
['death', 'hated']
['debut', 'tubed']
['decaf', 'faced']
['defer', 'freed']
['deify', 'edify']
['deign', 'dinge']
['denim', 'mined']
['dense', 'needs']
['desex', 'sexed']
['deter', 'treed']
['deuce', 'educe']
['dimer', 'mired', 'rimed']
['dinar', 'drain', 'nadir', 'ranid']
['dingy', 'dying']
['dirge', 'ridge']
['divan', 'viand']
['diver', 'drive']
['dolor', 'drool']
['donor', 'rondo']
['dowry', 'rowdy', 'wordy']
['drape', 'raped']
['drier', 'rider']
['drupe', 'prude']
['dusty', 'study']
['early', 'layer', 'relay']
['easel', 'lease']
['eaten', 'enate']
['edger', 'greed']
['egret', 'greet']
['eland', 'laden']
['elver', 'lever', 'revel']
['endow', 'owned']
['enrol', 'loner']
['enter', 'rente']
['eosin', 'noise']
['equip', 'pique']
['erase', 'saree']
['erect', 'terce']
['ester', 'reset', 'steer', 'teres', 'terse']
['ether', 'there', 'three']
['every', 'veery']
['exalt', 'latex']
['extra', 'taxer']
['facer', 'farce']
['faker', 'freak']
['fakir', 'kafir']
['felid', 'field']
['feral', 'flare']
['ferry', 'fryer']
['fetor', 'forte']
['fiend', 'fined']
['fiery', 'reify']
['filar', 'flair', 'frail']
['filer', 'flier', 'lifer', 'rifle']
['finer', 'infer']
['fired', 'fried']
['flesh', 'shelf']
['flour', 'fluor']
['fondu', 'found']
['forge', 'gofer']
['forth', 'froth']
['fount', 'futon']
['fries', 'serif']
['gamma', 'magma']
['gelid', 'glide']
['genip', 'ginep']
['genre', 'green']
['genus', 'negus']
['ghoul', 'lough']
['girth', 'right']
['glans', 'slang']
['glare', 'lager', 'large', 'regal']
['glary', 'gyral']
['goner', 'negro']
['goral', 'largo']
['gouty', 'guyot']
['grain', 'nigra']
['grape', 'pager']
['grasp', 'sprag']
['grate', 'great']
['grist', 'grits']
['grown', 'wrong']
['gusty', 'gutsy']
['hadji', 'jihad']
['halon', 'lohan']
['hater', 'heart']
['heaps', 'phase', 'shape']
['helot', 'hotel', 'thole']
['hills', 'shill']
['hinge', 'neigh']
['hokum', 'khoum']
['hooks', 'shook']
['horse', 'shore']
['horst', 'short']
['ictal', 'tical']
['idler', 'riled']
['ilama', 'lamia']
['ilxxx', 'lxxxi']
['inapt', 'paint']
['incur', 'runic']
['inert', 'inter', 'niter', 'nitre', 'trine']
['ingot', 'tigon']
['inkle', 'liken']
['inner', 'niner', 'renin']
['inset', 'stein', 'tsine']
['intra', 'riant', 'train']
['inure', 'urine']
['irons', 'rosin']
['islet', 'stile']
['jaunt', 'junta']
['kiley', 'kylie']
['knawe', 'waken']
['knead', 'naked']
['labor', 'lobar']
['laird', 'larid']
['lansa', 'nasal']
['lapin', 'plain']
['lapse', 'sepal']
['learn', 'renal']
['leash', 'shale']
['least', 'slate', 'stale', 'steal', 'stela', 'tesla']
['legin', 'ligne']
['lemon', 'melon']
['leper', 'repel']
['lexis', 'silex']
['lingo', 'login']
['links', 'slink']
['liter', 'litre', 'tiler']
['louse', 'ousel']
['lower', 'rowel']
['lumpy', 'plumy']
['lunar', 'ulnar']
['lxiii', 'xliii']
['lxvii', 'xlvii']
['lxxiv', 'lxxvi']
['macho', 'mocha']
['manse', 'means', 'names']
['maser', 'smear']
['mated', 'tamed']
['mates', 'steam']
['matey', 'meaty']
['mayor', 'moray']
['merit', 'miter', 'mitre', 'remit', 'timer']
['meter', 'metre', 'retem']
['metis', 'smite', 'times']
['molar', 'moral']
['monad', 'nomad']
['motet', 'totem']
['mount', 'muton']
['mover', 'vomer']
['moxie', 'oxime']
['muser', 'serum']
['nasty', 'tansy']
['nauch', 'nucha']
['navel', 'venal']
['nerve', 'never']
['nexus', 'unsex']
['night', 'thing']
['nisus', 'sinus']
['north', 'thorn']
['noted', 'toned']
['oiled', 'oldie']
['oiler', 'oriel']
['olive', 'voile']
['onset', 'stone']
['optic', 'picot', 'topic']
['orach', 'roach']
['orpin', 'prion']
['other', 'throe']
['ottar', 'troat']
['otter', 'torte', 'toter']
['ought', 'tough']
['outer', 'outre', 'route']
['overt', 'trove', 'voter']
['owlet', 'towel']
['pagan', 'panga']
['palas', 'salpa']
['palsy', 'splay']
['panel', 'penal', 'plane']
['parer', 'raper']
['parts', 'sprat', 'strap']
['parvo', 'vapor']
['pasta', 'patas']
['paste', 'spate']
['pasty', 'patsy']
['pater', 'prate', 'taper']
['pedal', 'plead']
['penis', 'snipe', 'spine']
['peril', 'plier']
['petal', 'plate', 'pleat']
['piles', 'spiel', 'spile']
['pinto', 'piton', 'point']
['pipul', 'pupil']
['piste', 'spite', 'stipe']
['plyer', 'reply']
['poler', 'prole']
['poser', 'prose', 'spore']
['prise', 'spire']
['proto', 'troop']
['punks', 'spunk']
['puree', 'rupee']
['purse', 'sprue', 'super']
['pursy', 'syrup']
['quiet', 'quite']
['quote', 'toque']
['raita', 'riata', 'taira', 'tiara']
['raspy', 'spray']
['ravel', 'velar']
['reins', 'resin', 'rinse', 'risen', 'serin']
['repot', 'toper', 'trope']
['resew', 'sewer']
['rival', 'viral']
['rogue', 'rouge']
['roost', 'roots', 'torso']
['rumba', 'umbra']
['saber', 'sabre']
['sadhe', 'shade']
['saint', 'satin', 'stain']
['salmi', 'simal']
['salon', 'solan']
['salty', 'slaty']
['salve', 'slave', 'valse']
['sated', 'stead']
['satyr', 'stray']
['scape', 'space']
['scion', 'sonic']
['sente', 'teens', 'tense']
['serow', 'sower', 'worse']
['serve', 'sever', 'verse']
['servo', 'verso']
['setup', 'upset']
['sewed', 'weeds']
['share', 'shear']
['sherd', 'shred']
['shoot', 'sooth']
['shout', 'south']
['sidle', 'slide']
['sinew', 'swine']
['skate', 'stake', 'steak']
['skint', 'stink']
['skirt', 'stirk']
['slain', 'snail']
['sleet', 'steel', 'stele']
['slime', 'smile']
['sloop', 'spool']
['snake', 'sneak']
['snoop', 'spoon']
['snout', 'tonus']
['spirt', 'sprit', 'strip']
['sport', 'strop']
['spots', 'stops']
['spout', 'stoup']
['spurt', 'turps']
['stalk', 'talks']
['state', 'taste', 'testa']
['stoat', 'toast']
['stork', 'torsk']
['straw', 'swart']
['strew', 'trews', 'wrest']
['strut', 'trust']
['swage', 'wages']
['swear', 'wares']
['sweat', 'tawse', 'waste']
['swing', 'wings']
['sword', 'words']
['taint', 'titan']
['talon', 'tonal']
['tater', 'tetra', 'treat']
['tenia', 'tinea']
['tenno', 'tenon', 'tonne']
['tenor', 'toner']
['throw', 'worth', 'wroth']
['tilde', 'tiled']
['tired', 'tried']
['titer', 'titre', 'trite']
['toady', 'today']
['trade', 'tread']
['trail', 'trial']
['trout', 'tutor']
['unbar', 'urban']
['unite', 'untie']
['uveal', 'value']
['valor', 'volar']
['vogue', 'vouge']
['waker', 'wreak']
['weird', 'wired']
['whale', 'wheal']
['white', 'withe']
['xxxiv', 'xxxvi']
