['abbe', 'babe']
['abed', 'bead']
['abet', 'bate', 'beat', 'beta']
['able', 'bale', 'blae']
['abut', 'tabu', 'tuba']
['ache', 'each']
['acne', 'cane']
['acre', 'care', 'race']
['acyl', 'clay', 'lacy']
['adit', 'dita']
['adze', 'daze']
['aery', 'eyra', 'year']
['aide', 'idea']
['airs', 'sari']
['ajar', 'raja']
['akin', 'kina']
['alga', 'gala']
['allo', 'olla']
['alms', 'slam']
['alto', 'lota']
['alum', 'maul']
['amir', 'rima']
['ammo', 'mamo']
['amok', 'mako']
['anew', 'wane', 'wean']
['anil', 'nail']
['ante', 'neat']
['apar', 'para']
['aper', 'pare', 'pear', 'rape', 'reap']
['arch', 'char']
['arid', 'raid']
['aril', 'lair', 'liar', 'lira', 'rail', 'rial']
['arse', 'rase', 'sear']
['arts', 'star', 'tsar']
['arty', 'tray']
['ashy', 'shay']
['atom', 'moat']
['auld', 'dual', 'laud']
['aunt', 'tuna']
['aver', 'rave']
['avid', 'diva']
['awny', 'yawn']
['awry', 'wary']
['baht', 'bath']
['bait', 'tabi']
['bake', 'beak']
['balm', 'lamb']
['bane', 'bean']
['bard', 'brad', 'drab']
['bare', 'bear', 'brae']
['barn', 'bran']
['bast', 'bats', 'stab']
['baud', 'daub']
['beam', 'bema']
['bike', 'kibe']
['bleu', 'blue', 'lube']
['blot', 'bolt']
['blow', 'bowl']
['blur', 'burl']
['boat', 'bota']
['bogy', 'goby']
['bole', 'lobe']
['bone', 'ebon']
['bonk', 'knob']
['book', 'kobo']
['bore', 'robe']
['brag', 'garb', 'grab']
['buns', 'snub']
['burg', 'grub']
['bury', 'ruby']
['bust', 'stub']
['cade', 'dace']
['cafe', 'face']
['calk', 'lack']
['calm', 'clam']
['camo', 'coma']
['cape', 'pace']
['cark', 'rack']
['carp', 'crap']
['cask', 'sack']
['cast', 'scat']
['cedi', 'dice', 'iced']
['cero', 'core']
['chat', 'tach']
['chin', 'inch']
['chit', 'itch']
['chum', 'much']
['cive', 'vice']
['clod', 'cold']
['clot', 'colt']
['clxv', 'cxlv']
['coat', 'taco']
['coax', 'coxa']
['coin', 'icon']
['cone', 'once']
['conk', 'nock']
['cool', 'loco']
['cork', 'rock']
['corp', 'crop', 'porc']
['cote', 'ecto']
['cows', 'scow']
['cram', 'marc']
['cran', 'narc']
['cure', 'ecru']
['cusk', 'suck']
['cusp', 'scup']
['dago', 'goad']
['dahl', 'dhal']
['dais', 'disa', 'said']
['dale', 'deal', 'lade', 'lead']
['dalo', 'load']
['dame', 'made']
['dare', 'dear', 'read']
['darn', 'nard', 'rand']
['dart', 'trad']
['dash', 'shad']
['dawn', 'wand']
['dead', 'edda']
['deaf', 'fade']
['deem', 'meed']
['deer', 'reed']
['deli', 'idle', 'lied']
['demo', 'dome', 'mode']
['dent', 'tend']
['deny', 'dyne']
['dial', 'laid']
['diam', 'maid']
['diet', 'edit', 'tide', 'tied']
['diol', 'idol', 'lido']
['dire', 'ride']
['disk', 'skid']
['doer', 'redo']
['dole', 'lode']
['done', 'endo', 'node']
['doom', 'mood']
['door', 'odor', 'rood']
['dote', 'toed']
['drag', 'grad']
['draw', 'ward']
['dray', 'yard']
['drey', 'dyer']
['drop', 'prod']
['dune', 'nude']
['dust', 'stud']
['earn', 'near']
['east', 'eats', 'sate', 'seat', 'seta']
['easy', 'eyas']
['echt', 'etch', 'tech']
['eden', 'need']
['elan', 'lane', 'lean']
['else', 'lees', 'seel']
['emir', 'mire', 'rime']
['emit', 'item', 'mite', 'time']
['enol', 'lone']
['ento', 'note', 'tone']
['epha', 'heap']
['epos', 'peso', 'pose']
['ergo', 'goer', 'ogre']
['erst', 'rest']
['ever', 'veer']
['evil', 'live', 'veil', 'vile']
['fain', 'naif']
['fare', 'fear']
['fart', 'frat', 'raft']
['fate', 'feat']
['feel', 'flee']
['felt', 'left']
['fief', 'fife']
['file', 'lief', 'life']
['fire', 'rife']
['fist', 'sift']
['flea', 'leaf']
['flit', 'lift']
['flog', 'golf']
['flow', 'fowl', 'wolf']
['flue', 'fuel']
['foal', 'loaf']
['free', 'reef']
['fret', 'tref']
['gain', 'inga', 'nagi']
['gaol', 'goal']
['gape', 'page', 'peag']
['gari', 'ragi']
['gash', 'shag']
['gate', 'geta']
['gaur', 'guar', 'ruga']
['gear', 'rage']
['gird', 'grid']
['girt', 'grit', 'trig']
['glue', 'luge']
['gnat', 'tang']
['goat', 'toga']
['gory', 'gyro', 'orgy']
['grey', 'gyre']
['grin', 'ring']
['grip', 'prig']
['gulp', 'plug']
['gust', 'guts']
['haem', 'hame']
['hale', 'heal']
['halt', 'lath']
['hank', 'khan']
['hare', 'hear']
['hash', 'shah']
['hate', 'heat']
['haul', 'hula']
['heir', 'hire']
['hewn', 'when']
['hint', 'thin']
['hops', 'posh', 'shop']
['hose', 'shoe']
['host', 'shot', 'tosh']
['ides', 'side']
['iglu', 'ugli']
['ikon', 'kino', 'oink']
['ilxx', 'lxxi']
['imam', 'maim']
['inst', 'snit']
['jest', 'jets']
['jute', 'teju']
['kail', 'kali']
['kale', 'lake', 'leak']
['kayo', 'okay']
['keel', 'leek']
['keen', 'knee']
['keep', 'peek']
['kepi', 'pike']
['kiln', 'link']
['kiss', 'skis']
['kite', 'tike']
['knit', 'tink']
['know', 'wonk']
['lama', 'mala']
['lame', 'male', 'meal']
['lamp', 'palm']
['last', 'salt', 'slat']
['late', 'tael', 'tale', 'teal']
['lave', 'vale', 'veal']
['laze', 'zeal']
['leap', 'pale', 'peal', 'plea']
['leer', 'reel']
['lewd', 'weld']
['lien', 'line']
['lilt', 'till']
['lime', 'mile']
['limo', 'milo', 'moil']
['lino', 'lion', 'loin']
['lisp', 'slip']
['list', 'silt', 'slit']
['lite', 'tile']
['loam', 'mola']
['loge', 'ogle']
['loir', 'roil']
['loop', 'pool']
['loot', 'tool']
['lope', 'pole']
['lore', 'role']
['lose', 'sloe', 'sole']
['lost', 'lots', 'slot']
['loti', 'toil']
['loud', 'ludo']
['lout', 'tolu']
['love', 'vole']
['lump', 'plum']
['lure', 'rule']
['lust', 'slut']
['lwei', 'wile']
['lxii', 'xlii']
['lxiv', 'lxvi', 'xliv', 'xlvi']
['lyre', 'rely']
['main', 'mina']
['mane', 'mean', 'name']
['many', 'myna']
['mare', 'ream']
['mart', 'tram']
['mash', 'sham']
['mate', 'meat', 'tame', 'team']
['meet', 'teem']
['mesa', 'same', 'seam']
['mews', 'smew']
['mien', 'mine']
['miry', 'rimy']
['moan', 'noma']
['mono', 'moon']
['mope', 'poem', 'pome']
['morn', 'norm']
['mote', 'tome']
['must', 'smut']
['nape', 'neap', 'pane', 'pean']
['nark', 'rank']
['nary', 'yarn']
['nave', 'vane', 'vena']
['neon', 'none']
['nerd', 'rend']
['ness', 'sens']
['nest', 'sent']
['nett', 'tent']
['news', 'sewn']
['nose', 'sone']
['nous', 'onus']
['nuts', 'stun']
['okey', 'yoke']
['ombu', 'umbo']
['open', 'peon', 'pone']
['opus', 'soup']
['orad', 'road']
['over', 'rove']
['part', 'prat', 'rapt', 'tarp', 'trap']
['past', 'spat', 'taps']
['pate', 'peat', 'tape']
['pecs', 'spec']
['peri', 'pier', 'ripe']
['pest', 'step']
['poet', 'tope']
['pore', 'rope']
['post', 'spot', 'stop', 'tops']
['pram', 'ramp']
['prep', 'repp']
['prey', 'pyre']
['prom', 'romp']
['rain', 'rani']
['rale', 'real']
['rant', 'tarn']
['rare', 'rear']
['rasp', 'spar']
['rate', 'tare', 'tear']
['rent', 'tern']
['rete', 'tree']
['riel', 'rile']
['riot', 'tiro', 'trio']
['rise', 'sire']
['rite', 'tier', 'tire']
['rose', 'sore']
['rote', 'tore']
['rout', 'tour']
['roux', 'uxor']
['runt', 'turn']
['ruse', 'suer', 'sure', 'user']
['sail', 'sial']
['sale', 'seal']
['salp', 'slap']
['sang', 'snag']
['save', 'vase']
['seen', 'sene']
['seer', 'sere']
['sett', 'stet', 'test']
['shut', 'thus', 'tush']
['shwa', 'wash']
['sign', 'sing']
['silo', 'soil']
['sink', 'skin']
['skip', 'spik']
['snap', 'span']
['snip', 'spin']
['snog', 'song']
['snot', 'tons']
['snow', 'sown']
['snug', 'sung']
['stew', 'west']
['stow', 'swot']
['swad', 'wads']
['sway', 'ways', 'yaws']
['take', 'teak']
['tatu', 'taut']
['tort', 'trot']
['town', 'wont']
['troy', 'tyro']
['twat', 'watt']
['uvea', 'veau']
['vein', 'vine']
['veto', 'vote']
['view', 'wive']
['wake', 'weak', 'weka']
['wale', 'weal']
['ware', 'wear']
['warp', 'wrap']
['weir', 'wire']
['xciv', 'xcvi']
['xxiv', 'xxvi']
['xxix', 'xxxi']
