['      ', '      ', '      ']
['abient', 'binate']
['aboard', 'aborad', 'abroad']
['acarid', 'cardia']
['acinar', 'arnica']
['action', 'atonic', 'cation']
['adhere', 'header']
['adient', 'detain']
['adored', 'deodar']
['adsorb', 'boards']
['affair', 'raffia']
['afield', 'failed']
['agnise', 'easing']
['agonal', 'analog']
['agreed', 'dragee', 'geared']
['ahorse', 'ashore', 'hoarse']
['aigret', 'gaiter', 'triage']
['ailing', 'nilgai']
['airman', 'marina']
['albedo', 'doable']
['albite', 'bletia']
['alcove', 'coeval']
['algoid', 'dialog']
['alined', 'denial']
['allure', 'laurel']
['almond', 'dolman']
['alpine', 'penial', 'pineal']
['alumna', 'manual']
['alvine', 'valine', 'veinal', 'venial']
['ambler', 'marble', 'ramble']
['amenia', 'anemia']
['amerce', 'raceme']
['anemic', 'cinema', 'iceman']
['angled', 'dangle', 'lagend']
['animal', 'lamina', 'manila']
['anlage', 'galena']
['anoint', 'nation']
['anomic', 'camion', 'conima', 'manioc']
['anther', 'thenar']
['antler', 'rental']
['aorist', 'rosita', 'satori']
['append', 'napped']
['applet', 'lappet']
['argent', 'garnet']
['ariled', 'derail']
['armful', 'fulmar']
['arming', 'margin']
['armpit', 'impart']
['arpent', 'entrap', 'parent', 'trepan']
['arrest', 'raster', 'starer']
['artist', 'strait']
['ascent', 'secant', 'stance']
['ashbin', 'banish']
['asking', 'gaskin']
['aslant', 'lansat']
['asleep', 'elapse', 'please']
['aspire', 'paries', 'praise', 'spirea']
['assist', 'stasis']
['astral', 'tarsal']
['astute', 'statue']
['atrial', 'lariat', 'latria']
['attire', 'ratite']
['attune', 'nutate', 'tauten']
['augend', 'unaged']
['avocet', 'octave']
['avulse', 'values']
['awning', 'waning']
['badger', 'garbed']
['bagger', 'beggar']
['baleen', 'enable']
['bantam', 'batman']
['barbel', 'rabble']
['barbet', 'rabbet']
['barely', 'barley', 'bleary']
['barong', 'brogan']
['barony', 'baryon']
['baster', 'breast']
['bather', 'breath']
['battle', 'tablet']
['bawler', 'warble']
['beater', 'berate', 'rebate']
['bedlam', 'beldam', 'blamed']
['bedrid', 'bidder']
['begird', 'bridge']
['bestir', 'bister', 'bistre']
['binary', 'brainy']
['binder', 'inbred', 'rebind']
['blower', 'bowler']
['boater', 'borate', 'rebato']
['boiled', 'bolide']
['bonzer', 'bronze']
['booger', 'goober']
['boulle', 'lobule']
['braise', 'rabies']
['bridal', 'ribald']
['brumal', 'lumbar']
['brunet', 'bunter']
['buffer', 'rebuff']
['bugler', 'burgle']
['burble', 'lubber', 'rubble']
['burden', 'burned']
['bustle', 'sublet', 'subtle']
['cabala', 'calaba']
['cackel', 'cackle']
['cadent', 'canted', 'decant']
['caffer', 'caffre']
['caiman', 'maniac']
['caller', 'cellar', 'recall']
['calque', 'claque']
['canter', 'nectar', 'recant', 'trance']
['cantle', 'cental', 'lancet']
['cantor', 'carton', 'craton']
['capote', 'toecap']
['caring', 'racing']
['carpel', 'parcel', 'placer']
['cartel', 'claret', 'rectal']
['carved', 'craved']
['carven', 'cavern', 'craven']
['cashed', 'chased']
['casque', 'sacque']
['caster', 'recast']
['castle', 'cleats']
['casual', 'causal']
['catsup', 'upcast']
['caveat', 'vacate']
['cedarn', 'dancer']
['censer', 'screen', 'secern']
['center', 'recent', 'tenrec']
['cerate', 'create', 'ecarte']
['cereal', 'relace']
['cerium', 'uremic']
['cerous', 'course', 'source']
['cesium', 'miscue']
['chapel', 'pleach']
['chaser', 'eschar', 'search']
['chaste', 'sachet', 'scathe']
['chesty', 'scythe']
['chicle', 'cliche']
['choice', 'echoic']
['chokey', 'hockey']
['chorea', 'orache']
['chrism', 'smirch']
['cinque', 'quince']
['circle', 'cleric']
['cither', 'thrice']
['citrin', 'nitric']
['citrus', 'rictus', 'rustic']
['clawed', 'declaw']
['client', 'lectin', 'lentic']
['clonus', 'consul']
['closer', 'cresol']
['cohere', 'reecho']
['coiffe', 'office']
['coiled', 'docile']
['colter', 'lector']
['combat', 'tombac']
['coming', 'gnomic']
['comity', 'myotic']
['condor', 'cordon']
['conker', 'reckon']
['copula', 'cupola']
['corked', 'docker']
['corker', 'rocker']
['corona', 'racoon']
['corset', 'escort', 'scoter', 'sector']
['cosine', 'oscine']
['couthy', 'touchy']
['covert', 'vector']
['coyote', 'oocyte']
['cradle', 'credal']
['crater', 'tracer']
['credit', 'direct']
['crocus', 'succor']
['crosse', 'scores']
['croupe', 'recoup']
['crusty', 'curtsy']
['curdle', 'curled']
['cuscus', 'succus']
['cutlet', 'cuttle']
['dagame', 'damage']
['dagger', 'ragged']
['daimon', 'domain']
['daleth', 'halted']
['damned', 'demand', 'madden']
['dampen', 'madnep']
['dander', 'darned']
['dandle', 'landed']
['danger', 'gander', 'garden']
['darken', 'ranked']
['darter', 'retard', 'trader']
['dashed', 'shaded']
['dawdle', 'waddle']
['dealer', 'leader']
['dearth', 'hatred', 'thread']
['debase', 'seabed']
['decree', 'recede']
['deduce', 'deuced']
['defang', 'fanged']
['deform', 'formed']
['defray', 'frayed']
['dehorn', 'horned']
['dentin', 'indent', 'intend', 'tinned']
['denude', 'dudeen']
['depart', 'parted', 'petard']
['depone', 'opened']
['dermal', 'medlar']
['desalt', 'salted']
['desert', 'rested']
['design', 'signed']
['desire', 'reside']
['desorb', 'sorbed']
['despot', 'posted']
['detail', 'dilate', 'tailed']
['detent', 'netted']
['detest', 'tested']
['detour', 'routed']
['devoir', 'voider']
['diaper', 'paired']
['dibber', 'ribbed']
['diddle', 'lidded']
['digger', 'rigged']
['dimmer', 'rimmed']
['dinero', 'ironed']
['dingle', 'engild']
['dipper', 'ripped']
['domine', 'monied']
['dongle', 'golden']
['downer', 'wonder']
['dowser', 'drowse']
['draped', 'padder']
['drawer', 'reward', 'warder']
['dreary', 'yarder']
['driven', 'verdin']
['drogue', 'gourde', 'rouged']
['duffel', 'duffle']
['duster', 'rusted']
['eaglet', 'legate']
['earned', 'endear']
['earner', 'nearer']
['earthy', 'hearty']
['editor', 'triode']
['eighth', 'height']
['elater', 'relate']
['emigre', 'regime']
['empire', 'premie']
['enamel', 'melena']
['enamor', 'moaner']
['encase', 'seance']
['endive', 'veined']
['endure', 'enured']
['enfold', 'fondle']
['englut', 'gluten']
['engram', 'manger']
['enlist', 'listen', 'silent', 'tinsel']
['ensile', 'senile', 'silene']
['epical', 'plaice']
['epigon', 'pigeon']
['equipt', 'piquet']
['erbium', 'imbrue']
['eringo', 'ignore', 'region']
['errant', 'ranter']
['erring', 'ringer']
['eryngo', 'groyne']
['escarp', 'parsec', 'scrape', 'secpar']
['espial', 'lipase']
['esprit', 'priest', 'sprite', 'stripe']
['estrus', 'russet', 'tusser']
['etamin', 'inmate']
['ethnos', 'honest']
['evilly', 'lively', 'vilely']
['except', 'expect']
['fakery', 'freaky']
['fardel', 'flared']
['farmer', 'framer']
['faster', 'strafe']
['fender', 'ferned']
['ferule', 'refuel']
['fidget', 'gifted']
['filler', 'refill']
['filter', 'lifter', 'trifle']
['finder', 'friend']
['finely', 'lenify']
['finest', 'infest']
['finger', 'fringe']
['fleshy', 'shelfy']
['foetal', 'folate']
['foetor', 'footer']
['forest', 'foster']
['former', 'reform']
['friary', 'rarify']
['fringy', 'frying']
['gadget', 'tagged']
['gainer', 'reagin', 'regain']
['gainly', 'laying']
['galere', 'regale']
['galore', 'gaoler']
['ganger', 'grange', 'nagger']
['gaping', 'paging']
['gargle', 'lagger']
['garret', 'garter', 'grater']
['genial', 'linage']
['gerund', 'nudger']
['gilder', 'girdle', 'glider', 'ridgel']
['gingko', 'ginkgo']
['globin', 'goblin']
['gnetum', 'nutmeg']
['goiter', 'goitre']
['grader', 'regard']
['grison', 'signor']
['grouse', 'rugose']
['grower', 'regrow']
['grudge', 'rugged']
['gunnel', 'lungen']
['gurgel', 'gurgle', 'lugger']
['halloo', 'holloa']
['halter', 'lather']
['hanker', 'harken']
['hatter', 'threat']
['hawser', 'washer']
['hearer', 'rehear']
['heater', 'reheat']
['hegari', 'hegira']
['herein', 'inhere']
['herpes', 'sphere']
['hitter', 'tither']
['holdup', 'uphold']
['homage', 'ohmage']
['hornet', 'throne']
['hustle', 'sleuth']
['icecap', 'ipecac']
['impure', 'umpire']
['impute', 'uptime']
['incest', 'insect']
['indite', 'tineid']
['ingest', 'signet']
['inkpad', 'kidnap']
['inroad', 'ordain']
['insane', 'sienna']
['insert', 'sinter']
['insole', 'lesion']
['instar', 'strain']
['instep', 'spinet']
['insult', 'sunlit']
['insure', 'ursine']
['intern', 'tinner']
['inured', 'ruined']
['isomer', 'rimose']
['joiner', 'rejoin']
['kilter', 'kirtle']
['kindle', 'linked']
['labile', 'liable']
['ladder', 'raddle']
['lading', 'ligand']
['lament', 'mantel', 'mantle', 'mental']
['lascar', 'rascal', 'sacral', 'scalar']
['latent', 'latten', 'talent']
['latter', 'rattle']
['launce', 'unlace']
['layout', 'outlay']
['leaper', 'repeal']
['leased', 'sealed']
['leaver', 'reveal']
['lentil', 'lintel']
['lienal', 'lineal']
['lignin', 'lining']
['limper', 'prelim']
['linear', 'nailer']
['lineup', 'lupine']
['lingam', 'malign']
['linkup', 'uplink']
['lisper', 'pliers']
['litchi', 'lithic']
['litter', 'tilter']
['livery', 'verily']
['loader', 'ordeal', 'reload']
['lobate', 'oblate']
['loiter', 'toiler']
['loment', 'molten']
['looped', 'poodle']
['looper', 'pooler']
['looter', 'retool', 'rootle']
['lopper', 'propel']
['louden', 'nodule']
['louvar', 'ovular', 'valour']
['louver', 'velour']
['lovely', 'volley']
['lowest', 'lowset']
['lumber', 'rumble']
['lumpen', 'plenum']
['lumper', 'rumple']
['luster', 'lustre', 'result', 'rustle', 'sutler']
['lxviii', 'xlviii']
['lxxxiv', 'lxxxvi']
['lyrate', 'realty']
['madman', 'nammad']
['maiden', 'median']
['maiger', 'maigre', 'mirage']
['mailed', 'medial']
['mangey', 'mayeng']
['mantis', 'matins']
['mapper', 'pamper']
['marine', 'remain']
['marker', 'remark']
['masher', 'shmear']
['master', 'stream']
['meager', 'meagre']
['meanly', 'namely']
['mesial', 'samiel']
['meteor', 'remote']
['midden', 'minded']
['minder', 'remind']
['minuet', 'minute']
['molder', 'remold']
['monger', 'morgen']
['motmot', 'tomtom']
['mutism', 'summit']
['mutual', 'umlaut']
['myosin', 'simony']
['naiant', 'tannia']
['nebula', 'unable']
['nerita', 'retain', 'retina']
['nester', 'resent']
['neural', 'unreal']
['neuter', 'tenure', 'tureen']
['noesis', 'sonsie']
['noetic', 'notice']
['nudity', 'untidy']
['nudnik', 'unkind']
['nursed', 'sunder']
['offset', 'setoff']
['onager', 'orange']
['opener', 'reopen']
['oppugn', 'popgun']
['option', 'potion']
['organs', 'sarong']
['orpine', 'pernio']
['ostler', 'sterol']
['output', 'putout']
['oyster', 'storey']
['palter', 'plater']
['paltry', 'partly']
['pander', 'repand']
['papers', 'sapper']
['papery', 'prepay']
['pariah', 'raphia']
['parley', 'pearly', 'player', 'replay']
['parrot', 'raptor']
['passer', 'sparse']
['pastel', 'septal', 'staple']
['paster', 'repast']
['patent', 'patten']
['pathos', 'potash']
['patina', 'pinata', 'taipan']
['patrol', 'portal']
['patron', 'tarpon']
['paynim', 'pyinma']
['pedant', 'pentad']
['pelmet', 'temple']
['pelter', 'petrel']
['peplus', 'supple']
['perish', 'seriph']
['pester', 'preset']
['phrase', 'seraph', 'shaper']
['pincer', 'prince']
['pinite', 'tiepin']
['piolet', 'polite']
['pistol', 'spoilt']
['pitsaw', 'sawpit']
['plaint', 'pliant']
['planet', 'platen']
['popery', 'pyrope']
['porter', 'pretor', 'report']
['poster', 'presto']
['potman', 'tampon']
['poulet', 'tupelo']
['pouter', 'troupe']
['pronto', 'proton']
['purine', 'unripe']
['quoter', 'torque']
['racket', 'tacker']
['raetam', 'ramate']
['raiser', 'sierra']
['rapier', 'repair']
['rasher', 'sharer']
['rattan', 'tartan']
['reader', 'reread']
['recite', 'tierce']
['recuse', 'rescue', 'secure']
['redact', 'traced']
['relays', 'slayer']
['relive', 'revile']
['remora', 'roamer']
['rennet', 'tenner']
['resale', 'reseal', 'sealer']
['reseat', 'teaser']
['resect', 'secret']
['reseda', 'seared']
['reseed', 'seeder']
['resell', 'seller']
['resift', 'sifter', 'strife']
['resign', 'signer', 'singer']
['resist', 'sister']
['resize', 'seizer']
['resort', 'roster', 'sorter']
['retick', 'ticker']
['retort', 'rotter']
['revamp', 'vamper']
['revers', 'server']
['review', 'viewer']
['rework', 'worker']
['risque', 'squire']
['rotund', 'untrod']
['router', 'tourer']
['runway', 'unwary']
['sachem', 'schema']
['sacred', 'scared']
['saliva', 'salvia']
['salter', 'slater']
['salver', 'serval', 'slaver']
['sanity', 'satiny']
['sateen', 'senate']
['sawyer', 'swayer']
['scaler', 'sclera']
['seated', 'sedate', 'teased']
['serail', 'serial']
['sestet', 'tsetse']
['settee', 'testee']
['setter', 'street', 'tester']
['sewing', 'swinge']
['shiner', 'shrine']
['shiver', 'shrive']
['shriek', 'shrike']
['shumac', 'sumach']
['silver', 'sliver']
['skater', 'strake', 'streak']
['sleety', 'steely']
['snatch', 'stanch']
['solute', 'tousle']
['somber', 'sombre']
['sorbet', 'strobe']
['sorted', 'stored']
['sortie', 'triose']
['spinel', 'spline']
['sprout', 'stupor']
['stater', 'taster']
['stoner', 'tensor']
['stores', 'tosser']
['suture', 'uterus']
['tactic', 'tictac']
['teasel', 'teasle']
['teeter', 'terete']
['tilted', 'titled']
['timber', 'timbre']
['torpid', 'tripod']
['travel', 'varlet']
['triune', 'untier']
['turnup', 'upturn']
['twiner', 'winter']
['uncase', 'usance']
['united', 'untied']
['unlive', 'unveil']
['upwind', 'windup']
['virino', 'virion']
['wander', 'warden']
['welkin', 'winkle']
['widely', 'wieldy']
['wither', 'writhe']
